### ISSUE TITLE
React or JSX?

### ISSUE THREAD

**Issue by lassejlv** [rossrobino/domco#12]
Wil domco support react or jsx in the feature?

**Comment by rossrobino** [comment]
Hi @lassejlv 

I need to add some more examples to the docs or template to the create script. 

You can use JSX and React with domco right now. If you used the create script, change your +server file to .jsx/.tsx extension and it will work using hono/jsx. Here's an example of what your +server file would look like: https://hono.dev/docs/guides/jsx#usage

Remove the hono jsxImportSource from your tsconfig to default to React instead. 

Here are [steps to migrate](https://domco.robino.dev/migrate) an existing vite+react app to use domco. 

Let me know if that answers your question, thanks for your interest in the project!

**Comment by lassejlv** [comment]
Hi, thanks for the help. It would be great with a template or docs about it. Keep up the good work 🙂

**Comment by rossrobino** [comment]
I created a [domco-examples repository](https://github.com/rossrobino/domco-examples), it shows some DIY and some SSR framework examples.

Here's a link to the [react-router example](https://github.com/rossrobino/domco-examples/tree/main/apps/react-router) with SSR in case you are still interested. Thanks again for the feedback!
